[theme]
base = "dark"
primaryColor = "#A78BFA"
backgroundColor = "#050914"
secondaryBackgroundColor = "#0A1220"
textColor = "#F8FAFC"
font = "sans serif"

[server]
headless = true
maxUploadSize = 300

[browser]
gatherUsageStats = false

[client]
toolbarMode = "minimal"
